#include "ttype.h"

#define CASE_RETURN(X) case X: return #X

const char *ttype_to_string(ttype_t ttype) {
  switch (ttype) {
    CASE_RETURN(TT_UNKNOWN);
    CASE_RETURN(TT_COMMA);
    CASE_RETURN(TT_SEMICOLON);
    CASE_RETURN(TT_EQ);
    CASE_RETURN(TT_EQEQ);
    CASE_RETURN(TT_EXCLA);
    CASE_RETURN(TT_EXCLAEQ);
    CASE_RETURN(TT_LT);
    CASE_RETURN(TT_LE);
    CASE_RETURN(TT_GT);
    CASE_RETURN(TT_GE);
    CASE_RETURN(TT_AMP);
    CASE_RETURN(TT_BAR);
    CASE_RETURN(TT_PLUS);
    CASE_RETURN(TT_MINUS);
    CASE_RETURN(TT_ASTERISK);
    CASE_RETURN(TT_SLASH);
    CASE_RETURN(TT_PERCENT);
    CASE_RETURN(TT_LPAREN);
    CASE_RETURN(TT_RPAREN);
    CASE_RETURN(TT_LBRACE);
    CASE_RETURN(TT_RBRACE);
    CASE_RETURN(TT_LBRACKET);
    CASE_RETURN(TT_RBRACKET);
    CASE_RETURN(TT_INTEGER);
    CASE_RETURN(TT_CHAR);
    CASE_RETURN(TT_SYMBOL);
    CASE_RETURN(TT_KW_IF);
    CASE_RETURN(TT_KW_ELSE);
    CASE_RETURN(TT_KW_WHILE);
    CASE_RETURN(TT_KW_BREAK);
    CASE_RETURN(TT_KW_CONTINUE);
    CASE_RETURN(TT_KW_PUTI);
    CASE_RETURN(TT_KW_PUTC);
    CASE_RETURN(TT_KW_GETI);
    CASE_RETURN(TT_KW_GETC);
    CASE_RETURN(TT_KW_ARRAY);
    CASE_RETURN(TT_KW_HALT);
    CASE_RETURN(TT_KW_FUNC);
    CASE_RETURN(TT_KW_RETURN);
    CASE_RETURN(TT_KW_CONST);
    CASE_RETURN(TT_EOF);
  default:
    return "(UNDEFINED)";
  }
}
